version: "3.8"

services:
  web:
    build: .          # збираємо образ із поточної папки
    ports:
      - "8081:80"     # <зовнішній>:<внутрішній>
    restart: unless-stopped

jenkins:
  image: jenkins/jenkins:lts
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - jenkins_home:/var/jenkins_home
  user: root
